### ISSUE TITLE
微信分享二维码怎么出不来呢

### ISSUE THREAD

**Issue by bboym** [litten/BlogBackup#13]
<img src="http://s.jiathis.com/qrcode.php?url=https://github.com/bboym/2017/09/29/hello-world/" alt="微信分享二维码">

<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMYAAADGCAAAAACs8KCBAAACIklEQVR42u3aS26EMBAFwNz/0mQbKYJ5r00iYcqr0YDAxaLl/nx9xev4sX7/n/9ur968MDAwHss4Ltf1PWdX201ff4Lrt2NgYLyHcRbB8iB4/Zz8Ccl7MTAwMJKjXh6Uz+6ZHRwxMDAwWkYbjmefBgMDAyMPlEnpbeUJ/5SLY2BgPJCRV93///ef9DcwMDAexTjKNTvS3RVeT3eFgYGxNWOWgs5gbSOhHv7AwMDYmpGnpu3gRR5Yk3dFVAwMjK0Z7dbvHaRoj6QRBgMDY1PGeiE+SVlnYxnFIRIDA2NTxr0BsU1r82Ba9GMxMDC2YNxVPstbAuuNh2haBAMDYyNGUg5rm445sj1QFkdDDAyMrRnXjYG2BNampnkKvdTCxMDAeBSjtSabXrm/TWLr7isGBsYDGStjFnlrc1aYq4txGBgYL2CsJ59t0jtLmE93joGB8QJGHjrbolublM5anhgYGLsyZgMQbSI6C7jJMfFDuQ0DA2MLxvW6awyiGJWIQ3kEwMDA2Igxe3SCT0pseQHuAwYDA+NljCNYd7UqZ2W4qOeJgYGxHaPdboJv3zs7sGJgYOzNOMqVf5uVtLY+XGJgYGzNyNeMtFKeq4ctMDAwtmYkQfbesLgecDEwMN7JmDUDZiNfSckvLw5iYGBgrBf310t70efAwMDAGDFa5KzJioGB8R5GksTmwbQNr21xDQMD422MldSx7TlcI9sgi4GB8QLGN2sq+gimxwvEAAAAAElFTkSuQmCC" alt="微信分享二维码">

你这个是怎么出来的呢

**Comment by JinJieGu** [comment]
我也是，微信二维码图片加载不出来，是哪里配置不正确吗

**Comment by caozhengbo** [comment]
放到git上，复制图片的路径
