### ISSUE TITLE
关于标签功能

### ISSUE THREAD

**Issue by chengsmart** [litten/BlogBackup#4]
litten大神你好，我使用了你制作的tpl，但是我找了好久没有找到这个模板的标签配置在哪里，能否指点一下？

**Comment by litten** [comment]
标签是hexo的本身功能，与主题无关。
当你的文章带有标签时，最终编译就会自动生成tags文件夹，并不是通过配置去设定的。

**Comment by chengsmart** [comment]
多谢大神，给力及时
