### ISSUE TITLE
可否转载一篇文章？关于反爬虫的，觉得挺有意思

### ISSUE THREAD

**Issue by buaanie** [litten/BlogBackup#9]
你好，最近在使用 hexo 写博客，发现你的theme，并且还有不错的文章，对于[反爬虫](http://litten.me/2017/07/09/prevent-spiders/) 这篇很感兴趣，自己也遇到过里面的一些案例，觉得你总结得很好，不知道可否转载（会注明）。

**Comment by litten** [comment]
可以
